import Head from 'next/head'
import { AiFillGithub } from "react-icons/ai"
import { AiFillLinkedin } from "react-icons/ai"
import { AiFillYoutube } from "react-icons/ai"
import Project from './components/projects'
import ContactUs from './components/contact'
import axios from 'axios'
import { useState, useEffect } from 'react'
import React from 'react'
import Link from 'next/link'
import Contactpage from './Contactpage'


export default function Home() {
  return (
    <div>

      <Head >
        <title>Jashandeep Singh</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico"/>
      </Head>

      <main className='bg-gray-800 text-white'>
      
        <section className='min-h-screen'> 
        
        <nav className="lg: flex justify-between p-10 font-bold text-center">
          <p>Jashandeep Singh</p>

          
          <ul className='lg: flex space-x-10'>
            <li><a href='#projects'>Portfolio</a></li>
            <li><a href='#'>Resume</a></li>
            <li><a href='#contact'>Contact Me</a></li>
          </ul>
          
        </nav>
        

        
        <div className='text-center space-y-5 last:'>
          <h1>Jashandeep Singh</h1>
          <h2>Software Engineer</h2>
          <p className='max-w-500 px-20'>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Minima voluptatibus, porro voluptas placeat aperiam reiciendis quos voluptate officia illo saepe ea eveniet corrupti quas commodi eos? Blanditiis labore architecto explicabo!
          Corrupti fugiat suscipit hic delectus quod quaerat accusamus ut, numquam ab quasi expedita natus possimus soluta provident neque voluptatibus cum illo corporis recusandae consectetur distinctio architecto debitis quam? Magni, consectetur?</p>
        </div>

        <div className='flex justify-center space-x-5 text-5xl pt-10'>
            <a href='https://github.com/jashansingh303' target="_blank"><AiFillGithub/></a> 
            <a href='https://www.linkedin.com/in/jashandeep-singh-/' target="_blank"><AiFillLinkedin/></a>
            <AiFillYoutube/>
        </div>

        <div >
          <img src="/images/indian-man-sikh-svgrepo-com.svg" />
        </div>

        </section>

        <section className='pb-10' id='projects'>
          <h1 className='text-xl pl-10'>PROJECTS</h1>
          <div className='lg: flex gap-10 ml-10 mr-10 sm:flex-col pt-10'>
            <Project name="Project 1" description="Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi necessitatibus fugit ad molestias ut explicabo veritatis deserunt deleniti, velit aliquid at, blanditiis aliquam cupiditate nesciunt. Corporis a cumque laudantium id."
            tech1="HTML" tech2="Tailwind CSS" tech3 = "Javascript" tech4="ReactJS"/>

            <Project name="Project 2" description="Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi necessitatibus fugit ad molestias ut explicabo veritatis deserunt deleniti, velit aliquid at, blanditiis aliquam cupiditate nesciunt. Corporis a cumque laudantium id."
            tech1="HTML" tech2="Tailwind CSS" tech3 = "Javascript" tech4="ReactJS"/>

            <Project name="Project 3" description="Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi necessitatibus fugit ad molestias ut explicabo veritatis deserunt deleniti, velit aliquid at, blanditiis aliquam cupiditate nesciunt. Corporis a cumque laudantium id."
            tech1="HTML" tech2="Tailwind CSS" tech3 = "Javascript" tech4="ReactJS"/>
          </div>
        </section>

      <section id='contact'>
        <ContactUs/>
      </section>

      <input type="text" id="input1"  className='text-black'></input>
      <button>Get Data</button>

      </main>
    </div>
  )
}
